"""
app/SOAP_Note_generation/SOAP_request.py

Pydantic schemas for the SOAP Note Generation endpoint.
"""

from typing import Optional
from pydantic import BaseModel, Field


class SOAPNoteResponse(BaseModel):
    """Structured SOAP Note response generated by Gemini."""
    Subjective: str = Field(..., description="Patient-reported symptoms, history, and complaints")
    Objective: str = Field(..., description="Clinical findings, vitals, exam results, observed data")
    Assessment: str = Field(..., description="Doctor's diagnosis / clinical assessment / impression")
    Plan: str = Field(..., description="Treatment plan, medications, follow-up, next steps")
    input_token: Optional[str] = Field(default=None, description="Number of tokens in the prompt")
    output_token: Optional[str] = Field(default=None, description="Number of tokens in the generated response")


class SOAPErrorResponse(BaseModel):
    status: str = Field(default="error")
    message: str
